apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-0ofr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-0ofr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-0ofr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-0ofr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-0ofr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bmqt-tenant/rhtap-demo-app/hacbs-test-project-0ofr@sha256:7a35e42730ecc5ec795d5535d7c27e8dcd76123a5b978ce94df7f4ed9741e645
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
