apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0ofr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bmqt-tenant/rhtap-demo-app/hacbs-test-project-0ofr@sha256:7a35e42730ecc5ec795d5535d7c27e8dcd76123a5b978ce94df7f4ed9741e645
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
